title: "koon的博客"
description: "记录日常，整理思考，让文字慢慢生长。"
baseurl: ""
url: "https://kawf777.github.io"
lang: zh-CN
timezone: Asia/Shanghai
author: koon
markdown: kramdown
excerpt_separator: "<!--more-->"
plugins: [jekyll-feed, jekyll-seo-tag]
exclude: [README.md]
